# Generated by Django 5.0.4 on 2024-05-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char_icon",
                    models.CharField(
                        default="https://upload.wikimedia.org/wikipedia/commons/3/33/White_square_with_question_mark.png",
                        max_length=1500,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(1, "Male"), (2, "Female"), (3, "Non-Binary")],
                        default=3,
                    ),
                ),
                (
                    "species",
                    models.IntegerField(
                        choices=[
                            (1, "Deity"),
                            (2, "Guardian"),
                            (3, "Human"),
                            (4, "Umbra"),
                            (5, "Underland"),
                            (6, "Xerioplatis"),
                            (7, "Numen"),
                            (8, "Familiar"),
                        ],
                        default=1,
                    ),
                ),
                ("species_desc", models.CharField(max_length=100)),
                ("height_ft", models.CharField(max_length=5)),
                ("height_cm", models.IntegerField()),
                (
                    "fighting_style",
                    models.IntegerField(
                        choices=[
                            (1, "Doesnt fight"),
                            (2, "Physical fighter"),
                            (3, "Water"),
                            (4, "Earth"),
                            (5, "Fire"),
                            (6, "Electricity"),
                            (7, "Wind"),
                            (8, "Arcane"),
                            (9, "Ancient Magic"),
                        ],
                        default=1,
                    ),
                ),
                ("fighting_style_desc", models.CharField(max_length=500)),
                ("char_notes", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
