# Generated by Django 5.0.4 on 2024-05-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0002_artwork_content_characters_artwork_content_stories"),
        ("characters", "0001_initial"),
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="character_content",
            field=models.ManyToManyField(
                blank=True, related_name="character_content", to="artwork.artwork"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="character_stories",
            field=models.ManyToManyField(
                blank=True, related_name="character_stories", to="stories.story"
            ),
        ),
    ]
