# Generated by Django 5.0.4 on 2024-05-19 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0002_artwork_content_characters_artwork_content_stories"),
        ("characters", "0002_character_character_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="char_icon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="char_icon",
                to="artwork.artwork",
            ),
        ),
    ]
