# Generated by Django 5.0.4 on 2024-06-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0004_document"),
        ("characters", "0003_alter_character_char_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="character_document",
            field=models.ManyToManyField(
                blank=True, related_name="character_document", to="artwork.document"
            ),
        ),
    ]
