# Generated by Django 5.0.4 on 2024-09-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0004_character_character_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="body_type",
            field=models.IntegerField(
                choices=[(1, "Animal"), (2, "Anthro"), (3, "Human")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="height_cm",
            field=models.IntegerField(editable=False),
        ),
    ]
