# Generated by Django 5.0.4 on 2024-05-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0002_artwork_content_characters_artwork_content_stories"),
        ("characters", "0002_character_character_content_and_more"),
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="story_characters",
            field=models.ManyToManyField(
                blank=True, related_name="story_characters", to="characters.character"
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="story_content",
            field=models.ManyToManyField(
                blank=True, related_name="story_content", to="artwork.artwork"
            ),
        ),
    ]
