# Generated by Django 5.0.4 on 2024-06-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0004_document"),
        ("stories", "0003_alter_story_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="story_document",
            field=models.ManyToManyField(
                blank=True, related_name="story_document", to="artwork.document"
            ),
        ),
    ]
