# Generated by Django 5.0.4 on 2024-05-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_link", models.ImageField(upload_to="images/")),
                ("creator_name", models.CharField(max_length=100)),
                ("image_title", models.CharField(max_length=250)),
                ("image_description", models.TextField()),
                (
                    "art_type",
                    models.IntegerField(
                        choices=[(1, "Digital"), (2, "Traditional")], default=1
                    ),
                ),
                (
                    "finish_level",
                    models.IntegerField(
                        choices=[
                            (1, "Lined"),
                            (2, "Flat"),
                            (3, "Cel"),
                            (4, "Painted"),
                            (5, "Other"),
                        ],
                        default=1,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
