# Generated by Django 5.0.4 on 2024-05-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0001_initial"),
        ("characters", "0001_initial"),
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="content_characters",
            field=models.ManyToManyField(
                blank=True, related_name="content_characters", to="characters.character"
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="content_stories",
            field=models.ManyToManyField(
                blank=True, related_name="content_stories", to="stories.story"
            ),
        ),
    ]
