# Generated by Django 5.0.4 on 2024-06-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0002_artwork_content_characters_artwork_content_stories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="image_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
