# Generated by Django 5.0.4 on 2024-06-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0003_alter_artwork_image_description"),
        ("characters", "0003_alter_character_char_icon"),
        ("stories", "0003_alter_story_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_link", models.FileField(upload_to="documents/")),
                ("creator_name", models.CharField(max_length=100)),
                ("document_title", models.CharField(max_length=250)),
                ("document_description", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "document_characters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="document_characters",
                        to="characters.character",
                    ),
                ),
                (
                    "document_stories",
                    models.ManyToManyField(
                        blank=True, related_name="document_stories", to="stories.story"
                    ),
                ),
            ],
        ),
    ]
