# Generated by Django 5.0.4 on 2024-06-02 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0004_document"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artwork",
            old_name="image_title",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="document_title",
            new_name="title",
        ),
    ]
