# Generated by Django 5.0.4 on 2024-09-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artwork", "0006_document_document_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
